### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by Cyclops789**
docker containerizing support

### CODE REVIEW

**Comment by Cyclops789** [comment]
Can you rebuild the source files again?

**Comment by a-sync** [comment]
thanks, i will check it out, but im also working on a flyio compatible dockerfile, so i might just use my own version.

not sure what you want me to rebuild. i removed the built artifacts from the repo, since it is no longer required to be there to be deployable.

**Comment by Cyclops789** [comment]
That sounds awesome, I prefer to use Docker but I couldn't make the "npm run build" work inside the container, so its actually doesn't build anything.

**Comment by a-sync** [comment]
closing this as i added a working dockerfile and a docker-compose file to the repo that uses the official node image

**Pull request closed without merging**
